datamodule:
  target: datasets.MnistDataModule
  params:
    data_path: data
    ptm_path: PTM/vit-tiny-patch16-224
    batch_size: 256

model:
  target: models.MnistVit
  params:
    ptm_path: PTM/vit-tiny-patch16-224
    lr: 1.0e-5
    drop_rate: 0.5
    hidden_size: 512
    num_classes: 10

trainer:
  train:
    target: pytorch_lightning.Trainer
    precision: 16
    max_epochs: 3
    enable_progress_bar: True
    num_sanity_val_steps: 0
    # limit_train_batches: 1
    # limit_val_batches: 1
  test:
    target: pytorch_lightning.Trainer
    max_epochs: 1
    logger: False
    enable_progress_bar: False
    num_sanity_val_steps: 0
    enable_checkpointing: False
 
callbacks:
  train:
    rich_progress_bar:
      target: pytorch_lightning.callbacks.RichProgressBar
      leave: True

    model_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: checkpoints/
      save_top_k: 1
      monitor: valid_acc
      mode: max

    logger:
      target: callbacks.Logger

    indicator:
      target:  callbacks.Indicator
      monitor: valid_acc
      mode: max
    
    early_stopping:
      target: pytorch_lightning.callbacks.EarlyStopping
      verbose: False
      patience: 3
      monitor: valid_acc
      mode: max

  test:
    logger:
      target: callbacks.Logger

logger: null
  # target: pytorch_lightning.loggers.TensorBoardLogger
  # save_dir: logs/
